# Домашнее задание 1

## Задача 1

Задано два числа A и B. Необходимо вывести символ "<", если A < B, ">" , если A> B и "=", если A = B

**Ввод**

    В первой строке задается значение первого числа. Во второй строке задается значение второго числа.

**Вывод**

    В единственную строку выводится символ "<", ">" или "=" , без кавычек

**Пример**

Ввод:

    100
    200

Вывод:

    <

## Задача 2

В отделе работают 3 сотрудника, которые получают заработную плату в рублях (целое число). Требуется определить: на сколько зарплата самого высокооплачиваемого из них отличается от самого низкооплачиваемого.

**Ввод**

    В первой строке задается зарплата первого сотрудника.
    Во второй строке задается зарплата второго сотрудника.
    В третей строке задается зарплата третьего сотрудника.

**Вывод**

    В единственную строку выводится разница между максимальной и минимальной зарплатами.

**Пример**

Ввод:

    100
    200
    300

Вывод:

    200

## Задача 3

Вводится строка. Нужно вывести новую строку, состоящую из элементов первоначальной строки, находящихся на нечетных индексах. 0 – считается четным числом.

**Ввод**

    В единственную строку вводится первоначальная строка.

**Вывод**

    В единственную строку выводится строка состоящая из искомых символов.

**Пример**

Ввод:

    Сегодня мы изучаем Python

Вывод:

    еон ыиуамPto

## Задача 4

Вводится значения температуры в градусах Фаренгейта, необходимо перевести ее в градусы Цельсия и вывести результат на экран.

С=(F-32)×5÷9

**Ввод**

    В единственную строку вводится значение температуры в градусах Фаренгейта.

**Вывод**

    В единственную строку выводится результат вычисления согласно следующему примеру:
    Введенная температура 10.5 градусов Фаренгейта равна -11.94 градусов Цельсия

**Пример**

Ввод:

    10.5

Вывод:

    Введенная температура 10.5 градусов Фаренгейта равна -11.94 градусов Цельсия

**Примечания**

Вывод градусов Цельсия осуществляется с точностью до двух знаков после запятой с использованием форматирования строки. Вывод градусов Фаренгейта должно быть такое же, как при вводе (без округления)

## Задача 5

Вводится целое число. Если оно четырехзначное, то используя операции целочисленного деления и остаток от деления, найти сумму и произведение его цифр. Если число не четырехзначное, то вывести сообщение «Ошибка ввода».

**Ввод**

    В единственную строку вводится целочисленное число больше нуля.

**Вывод**

    В первой строке выводится результат суммы, согласно шаблону:
    Сумма числа 1234 равна 10
    Во второй строке выводится результат произведения, согласно шаблону:
    Произведение числа 1234 равна 24
    Если введённое число не соответствует условию (не четырёхзначное), то выводится «Ошибка ввода».

**Пример 1**

Ввод:

    1234

Вывод:

    Сумма числа 1234 равна 10
    Произведение числа 1234 равна 24

**Пример 2**

Ввод:

    123 

Вывод:

    Ошибка ввода

## Задача 6

Дано целое число N > 0. Если N — нечетное, то вывести произведение 1·3·...·N; если N — четное, то вывести произведение 2·4·...·N.

**Ввод**

    В единственную строку вводится целочисленное число больше нуля.

**Вывод**

    В единственную строку выводится результат произведения.

# Домашнее задание 2

## Задача 1

В списке, содержащем положительные и отрицательные целые числа, вычислить сумму четных положительных элементов.

**Ввод**

    В первой строке задается единственное число N > 0 – количество элементов списка.
    Вторая строка 1 элемент списка
    Третья строка 2 элемент списка
    и т.д.

**Вывод**

    В единственную строку выводится искомая сумма четных положительных элементов

**Пример**

Ввод

    5
    -1
    10
    0
    5
    6

Вывод

    16

**Примечания**

Гарантируется, что будет задано ровно N элементов списка.

Необходимо использовать метод для добавления аргументов в список

## Задача 2

В заданном списке найти сумму элементов, находящихся между минимальным и максимальным элементами. Сортировать список не нужно. Сами минимальный и максимальный элементы в сумму не включать.

**Ввод**

    В единственной строке задаются элементы списка через пробел.

**Вывод**

    В единственную строку выводится сумма элементов согласно условию.

**Пример 1**

Ввод

    2 4 1 7 10 5 8

Вывод

    7

Пояснение - минимальный элемент в списке 1, максимальный - 10. Между ними 7

**Пример 2**

Ввод

    3 8 4 2 0 7

Вывод

    6

Пояснение - минимальный элемент в списке 0, максимальный - 8. Между ними 4 и 2. Складываем, получаем 6

**Примечания**

Гарантируется, что в списке будет только один минимальный элемент и только один максимальный элемент.

## Задача 3

Вводится список, необходимо найти сумму всех его цифр. Если вводится отрицательное число, то знак минус необходимо игнорировать.

**Ввод**

    В единственной строке задаются элементы списка через запятую с пробелом.

**Вывод**

    В единственную строку выводится сумма цифр согласно условию.

**Пример**

Ввод

    12, 104, 81

Вывод

    17

**Примечания**

Например, если дан список [12, 104, 81], то сумма всех его цифр будет равна:

1 + 2 + 1 + 0 + 4 + 8 + 1 = 17

## Задача 4

Посчитать сумму элементов каждого столбца двухмерного списка.

**Ввод**

    В первую строку, через пробел, вводится размерность двумерного списка.
    Первый элемент - количество строк, второй элемент - количество столбцов.
    Далее в каждой строке вводятся элементы строки списка, через пробел.
    Каждая новая строка списка должна вводится с новой строки.

**Вывод**

    В единственную строку через пробел выводится сумма элементов столбцов.
    Сначала сумму элементов нулевого столбца, затем первого, второго и т.д.

**Пример**

Ввод

    4 2
    1 2
    3 4
    5 6
    7 8

Вывод

    16 20

## Задача 5

Заменить все отрицательные элементы в двухмерном массиве на ноль.

**Ввод**

    В первую строку, через пробел, вводится размерность двумерного списка.
    Первый элемент - количество строк, второй элемент - количество столбцов.
    Далее в каждой строке вводятся элементы строки списка, через пробел.
    Каждая новая строка списка должна вводится с новой строки.

**Вывод**

    В первой строке выводится нулевая строка списка, изменённая согласно условию, через запятую и пробел
    Во второй строке выводится первая строка списка, изменённая согласно условию, через запятую и пробел
    и т.д.

**Пример**

Ввод

    4 3
    -3 -2 1
    2 3 4
    -5 6 7
    8 9 0

Вывод

    0, 0, 1
    2, 3, 4
    0, 6, 7
    8, 9, 0

## Задача 6

Напишите программу, которая принимает на вход строку, и выводит слово, которое встречается во фразе чаще всего. Гарантируется, что такое слово будет только одно. Регистр слов не учитывается, знаки препинания в предложениях игнорируются.

**Ввод**

    В единственную строку вводится строка.

**Вывод**

    В единственную строку выводится искомое слово и то количество раз, сколько оно встретилось в тексте.
    Данные выводятся через запятую.

**Пример**

Ввод

    Напишите программу, которая принимает на вход строку, и выводит слово, которое встречается во фразе чаще всего. Гарантируется, что такое слово будет только одно. Регистр слов не учитывается, знаки препинания в предложениях игнорируются.

Вывод

    слово, 2

## Задача 7

Предположим в языке программирования Python нет функции возведения в степень. Необходимо написать программу, в которой будет функция возводящая введенное пользователем число в введенную пользователем степень.

**Ввод**

    В первую строку вводится количество пар: число – степень
    Во вторую строку вводится число и степень, в которую его нужно возвести. Ввод производится через пробел.
    и т.д.

**Вывод**

    В первую строку выводится результат возведения числа в заданную степень.
    и т.д.

**Пример**

Ввод

    5
    5 3
    3 9
    -3 10
    100 0
    0 100

Вывод

    125
    19683
    59049
    1
    0

**Примечания**

Гарантируется, что число, которое необходимо ввести в степень целое.

Гарантируется, что степень, в которое необходимо ввести число, целое и больше или равно нулю.

# Домашнее задание 3

## Задача 1

Вычислить сумму каждой строки двумерного списка заданного случайными целыми числами.

**Ввод**

    В первой строке через пробел задается пять значений.
    Первое и второе - количество строк и столбцов двумерного списка.
    Третье - инициализатор случайных чисел.
    Четвертое и пятое – минимальное и максимальное значение для генерации случайных чисел.
    Все значения целочисленные и больше нуля.

**Вывод**

    В первой строке выводится сумма элементов нулевой строки списка.
    Во второй строке выводится сумма элементов второй строки.
    и т.д.

**Пример**

Ввод

    3 4 25 1 100

Вывод

    178
    189
    175

**Примечания**

random.seed(x) - инициализатор случайных чисел, где x значение получаемое при вводе данных.

random.randint(a, b) - возвращает случайное число из определенного диапазона.

## Задача 2

В соответствии с законом, принимать участие в выборах в качестве избирателя, можно по достижении 18 лет на день голосования. Необходимо написать программу, которая выведет сообщение можно ли избирателю участвовать в выборах или нет.

**Ввод**

    В первой строке задается количество рассматриваемых избирателей и дата голосования, по шаблону «3, 16.03.2024»
    Во второй строке вводится ФИО первого избирателя и дата его рождения, по шаблону «Иванов Иван Иванович, 25.01.1980»
    В третей строке вводится ФИО второго избирателя и дата его рождения, по шаблону «Петров Иван Иванович, 25.01.2020»
    и т.д.

**Вывод**

    В первой строке выводиться информация по первому избирателю по шаблону «Иванов И.И. может участвовать в выборах»
    Во второй строке выводиться информация по второму избирателю по шаблону «Петров И.И. НЕ может участвовать в выборах»
    и т.д.

**Пример 1**

Ввод

    3, 16.03.2024
    Иванов Иван Иванович, 25.01.1980
    Петров Иван Иванович, 17.03.2006
    Сидоров Иван Иванович, 16.03.2006

Вывод

    Иванов И.И. может участвовать в выборах
    Петров И.И. НЕ может участвовать в выборах
    Сидоров И.И. может участвовать в выборах

**Пример 2**

Ввод

    3, 17.03.2024
    Иванов Иван Иванович, 25.01.1980
    Петров Иван Иванович, 17.03.2006
    Сидоров Иван Иванович, 16.03.2006

Вывод

    Иванов И.И. может участвовать в выборах
    Петров И.И. может участвовать в выборах
    Сидоров И.И. может участвовать в выборах

## Задача 3

Найдите наибольший общий делитель.

**Ввод**

    В единственную строку вводится два целочисленных положительных числа через пробел.

**Вывод**

    В единственную строку выводится их наибольший общий делитель.

**Пример**

Ввод

    594 7920

Вывод

    198

p.s. Про способы нахождения НОД (наибольший общий делитель) можно ещё почитать по [ссылке](https://pythonpip.ru/examples/nod-dvuh-chisel-v-python)

# Домашнее задание 4

## Задача 1

Работаем с локальным файлом `Набор_данных_по_Kaggle_120_летняя_история_Олимпийский_игр.csv` [ссылка на файл](https://disk.yandex.ru/i/ypxELGTJk5ojmA)

Найдите сколько всего строк в таблице не считая заголовка.

## Задача 2

Найдите сколько было лет, самому молодому участнику олимпийских игр?

    Олимпийские игры 1994 года, пол мужской
    Олимпийские игры 1992 года, пол мужской
    Олимпийские игры 1996 года, пол женский

## Задача 3

Какую долю составляют (не в процентах) соревнования по мужской спортивной гимнастике среди всех участников игр 1904 года? Округлите ответ до двух знаков после точки.

Подсказка: вам необходимы соревнования «Gymnastics Men's Individual All-Around, Apparatus Work»

## Задача 4

Найдите среднее арифметическое для роста девушек баскетболисток (название соревнования должно начинаться со слова «Basketball»), которые участвовали в играх 1988 года. Округлите ответ до двух знаков после точки.

## Задача 5

Найдите самую тяжелую (по весу) спортсменку игр 2008 года. В каком виде спорта она участвовала? Скопируйте в ответ название.

## Задача 6

Найдите соответствие. В скольких олимпиадах приняли участие?

    Aleksey Yuryevich Nemov
    Aleksey Petrovich Bondarenko
    Darya Vitalyevna Pishchalnikova

## Задача 7

Сколько золотых медалей в борьбе (Wrestling) выиграла Россия на Олимпиаде в 2008 году?

## Задача 8

Найдите разницу между количеством уникальных видов спорта на играх в 2004 и в 1972 годах.

# Домашнее задание 5

## Задача 1

Определить является ли строка палиндромом.

**Ввод**

    В единственной строке задается строка с текстом.

**Вывод**

    В единственной строке выводится True если строка является палиндромом и False если не является палиндромом.

**Пример 1**

Ввод

    А роза упала на лапу Азора...

Вывод

    True

**Пример 2**

Ввод

    Привет мир!!!

Вывод

    False

**Примечание**

Регистр слов не учитывается, знаки препинания и пробелы в строке необходимо исключить.

## Задача 2

Дана строка, посчитать сколько в ней гласных букв.

**Ввод**

    В единственной строке задается строка с текстом.

**Вывод**

    В единственной строке выводится количество гласных букв или -1 если их нет.

**Пример**

Ввод

    привет мир!!!

Вывод

    3

**Примечания**

Следующие буквы считаются гласными: а, у, о, ы, и, э, я, ю, ё, е.

Гарантируется, что текст будет состоять из цифр, знаков препинание и букв русского алфавита

## Задача 3

По заданным позициям элемента в двумерном списке необходимо вывести значение этого элемента или же указать, что такого элемента нет.

**Ввод**

    В первую строку, через пробел, вводится размерность двумерного списка и позиции элемента.
    Первый элемент - количество строк, второй элемент - количество столбцов, третий элемент - позиция по строке, четвертый элемент – позиция по столбцу.
    Далее в каждой строке вводятся элементы строки списка, через пробел.
    Каждая новая строка списка должна вводится с новой строки.

**Вывод**

    В единственную строку выводится значение элемента или сообщение «Позиция выходит за пределы списка».

**Пример 1**

Ввод

    3 2 0 1
    1 2
    3 4
    5 6

Вывод

    2

**Пример 2**

Ввод

    3 2 5 1
    1 2
    3 4
    5 6

Вывод

    Позиция выходит за пределы списка

## Задача 4

Кодирование строки.

Кодирование осуществляется следующим образом, подается строка 'aaaabbсaa' преобразуется в 'a4b2с1a2', то есть группы одинаковых символов исходной строки заменяются на этот символ и количество его повторений в этой позиции строки.

**Ввод**

    В единственную строку вводится первоначальная строка, которую необходимо закодировать.

**Вывод**

    В единственную строку выводится итоговая закодированная строка.

**Пример 1**

Ввод

    aaaabbcaa

Вывод

    a4b2c1a2

**Пример 2**

Ввод

    абв

Вывод

    а1б1в1

**Примечания**

Гарантируется, что входная строка будет состоять из букв русского и английского языка в нижнем регистре.

Гарантируется, что длина строки будет больше или равна одному символу.

Про **groupby()** информация по [ссылке](https://docs-python.ru/standart-library/modul-itertools-python/funktsija-groupby-modulja-itertools/)

## Задача 5

Напишите простой калькулятор, который считывает с пользовательского ввода три строки: первое число, второе число и операцию, после чего применяет операцию к введённым числам ("первое число" "операция" "второе число") и выводит результат на экран (в консоль).

Поддерживаемые операции: +, -, /, *, mod, pow, div, где

    mod — это взятие остатка от деления,
    pow — возведение в степень,
    div — целочисленное деление.

Если выполняется деление и второе число равно 0, необходимо выводить строку "Деление на 0!".

Если операция не определена, то выводится сообщение «Ошибка ввода».

Обратите внимание, что на вход программе приходят вещественные числа.

**Ввод**

    В первою строку вводится первое число.
    Во вторую строку вводится второе число.
    В третью строку вводится операция.

**Вывод**

    В единственную строку выводится результат.

**Пример 1**

Ввод

    5
    5
    +

Вывод

    10.0

**Пример 2**

Ввод

    5
    0
    /

Вывод

    Деление на 0!

**Пример 3**

Ввод

    5
    5
    5

Вывод

    Ошибка ввода