# Домашнее задание 1

## Задача 1

Задано два числа A и B. Необходимо вывести символ "<", если A < B, ">" , если A> B и "=", если A = B

**Ввод**

    В первой строке задается значение первого числа. Во второй строке задается значение второго числа.

**Вывод**

    В единственную строку выводится символ "<", ">" или "=" , без кавычек

**Пример**

Ввод:

    100
    200

Вывод:

    <

In [ ]:
a = int(input())
b = int(input())

if a < b:
    print('<')
elif a > b:
    print('>')
else:
    print('=')

## Задача 2

В отделе работают 3 сотрудника, которые получают заработную плату в рублях (целое число). Требуется определить: на сколько зарплата самого высокооплачиваемого из них отличается от самого низкооплачиваемого.

**Ввод**

    В первой строке задается зарплата первого сотрудника.
    Во второй строке задается зарплата второго сотрудника.
    В третей строке задается зарплата третьего сотрудника.

**Вывод**

    В единственную строку выводится разница между максимальной и минимальной зарплатами.

**Пример**

Ввод:

    100
    200
    300

Вывод:

    200

In [ ]:
rab1 = int(input())
rab2 = int(input())
rab3 = int(input())
if rab1 >= rab2 and rab1 >= rab3:
    max = rab1
elif rab2 >= rab1 and rab2 >= rab3:
    max = rab2
else:
    max = rab3
if rab1 <= rab2 and rab1 <= rab3:
    min = rab1
elif rab2 <= rab1 and rab2 <= rab3:
    min = rab2
else:
    min = rab3

print(max - min)

## Задача 3

Вводится строка. Нужно вывести новую строку, состоящую из элементов первоначальной строки, находящихся на нечетных индексах. 0 – считается четным числом.

**Ввод**

    В единственную строку вводится первоначальная строка.

**Вывод**

    В единственную строку выводится строка состоящая из искомых символов.

**Пример**

Ввод:

    Сегодня мы изучаем Python

Вывод:

    еон ыиуамPto

In [ ]:
text = input()
print(text[1::2])  # Вариант решения через срез. Можно было решить через for, но так получается короче и проще

## Задача 4

Вводится значения температуры в градусах Фаренгейта, необходимо перевести ее в градусы Цельсия и вывести результат на экран.

С=(F-32)×5÷9

**Ввод**

    В единственную строку вводится значение температуры в градусах Фаренгейта.

**Вывод**

    В единственную строку выводится результат вычисления согласно следующему примеру:
    Введенная температура 10.5 градусов Фаренгейта равна -11.94 градусов Цельсия

**Пример**

Ввод:

    10.5

Вывод:

    Введенная температура 10.5 градусов Фаренгейта равна -11.94 градусов Цельсия

**Примечания**

Вывод градусов Цельсия осуществляется с точностью до двух знаков после запятой с использованием форматирования строки. Вывод градусов Фаренгейта должно быть такое же, как при вводе (без округления)

In [ ]:
vvod = float(input())
print(f"Введенная температура {vvod} градусов Фаренгейта равна {(vvod - 32) * 5 / 9 :.2f} градусов Цельсия")

## Задача 5

Вводится целое число. Если оно четырехзначное, то используя операции целочисленного деления и остаток от деления, найти сумму и произведение его цифр. Если число не четырехзначное, то вывести сообщение «Ошибка ввода».

**Ввод**

    В единственную строку вводится целочисленное число больше нуля.

**Вывод**

    В первой строке выводится результат суммы, согласно шаблону:
    Сумма числа 1234 равна 10
    Во второй строке выводится результат произведения, согласно шаблону:
    Произведение числа 1234 равна 24
    Если введённое число не соответствует условию (не четырёхзначное), то выводится «Ошибка ввода».

**Пример 1**

Ввод:

    1234

Вывод:

    Сумма числа 1234 равна 10
    Произведение числа 1234 равна 24

**Пример 2**

Ввод:

    123 

Вывод:

    Ошибка ввода

In [ ]:
vvod = int(input())
if vvod // 1000 != 0 and vvod // 1000 < 10 and vvod // 1000 > -10:
    n0 = vvod % 10
    n1 = vvod // 10 % 10
    n2 = vvod // 100 % 10
    n3 = vvod // 1000
    summ = n0 + n1 + n2 + n3
    multiplication = n0 * n1 * n2 * n3
    print(f'Сумма числа {vvod} равна {summ}')
    print(f'Произведение числа {vvod} равна {multiplication}')
else:
    print('Ошибка ввода')

## Задача 6

Дано целое число N > 0. Если N — нечетное, то вывести произведение 1·3·...·N; если N — четное, то вывести произведение 2·4·...·N.

**Ввод**

    В единственную строку вводится целочисленное число больше нуля.

**Вывод**

    В единственную строку выводится результат произведения.

In [ ]:
vvod = int(input())  # Решение через while
result = 1
if vvod % 2 == 0:
    i = 2
    while i <= vvod:
        result = result * i
        i += 2
else:
    i = 1
    while i <= vvod:
        result = result * i
        i += 2
print(result)

In [ ]:
vvod = int(input())  # Решение через range
result = 1
for i in range(2 - (vvod % 2), vvod + 1, 2):
    result *= i
print(result)

# Домашнее задание 2

## Задача 1

В списке, содержащем положительные и отрицательные целые числа, вычислить сумму четных положительных элементов.

**Ввод**

    В первой строке задается единственное число N > 0 – количество элементов списка.
    Вторая строка 1 элемент списка
    Третья строка 2 элемент списка
    и т.д.

**Вывод**

    В единственную строку выводится искомая сумма четных положительных элементов

**Пример**

Ввод

    5
    -1
    10
    0
    5
    6

Вывод

    16

**Примечания**

Гарантируется, что будет задано ровно N элементов списка.

Необходимо использовать метод для добавления аргументов в список

In [ ]:
nums = int(input())
summ_lst = 0
for i in range(nums):
    j = int(input())
    if j > 0 and j % 2 == 0:
        summ_lst += j

print(summ_lst)

## Задача 2

В заданном списке найти сумму элементов, находящихся между минимальным и максимальным элементами. Сортировать список не нужно. Сами минимальный и максимальный элементы в сумму не включать.

**Ввод**

    В единственной строке задаются элементы списка через пробел.

**Вывод**

    В единственную строку выводится сумма элементов согласно условию.

**Пример 1**

Ввод

    2 4 1 7 10 5 8

Вывод

    7

Пояснение - минимальный элемент в списке 1, максимальный - 10. Между ними 7

**Пример 2**

Ввод

    3 8 4 2 0 7

Вывод

    6

Пояснение - минимальный элемент в списке 0, максимальный - 8. Между ними 4 и 2. Складываем, получаем 6

**Примечания**

Гарантируется, что в списке будет только один минимальный элемент и только один максимальный элемент.

In [ ]:
spisok = list(map(int,input().split()))

min_index = spisok.index(min(spisok))
max_index = spisok.index(max(spisok))

if min_index < max_index:
    print(sum(spisok[min_index + 1 : max_index]))
else:
    print(sum(spisok[max_index + 1 : min_index]))

In [ ]:
# Альтернативный способ обработки ввода

spisok = [int(n) for n in input().split()]

min_index = spisok.index(min(spisok))
max_index = spisok.index(max(spisok))

if min_index < max_index:
    print(sum(spisok[min_index + 1 : max_index]))
else:
    print(sum(spisok[max_index + 1 : min_index]))

## Задача 3

Вводится список, необходимо найти сумму всех его цифр. Если вводится отрицательное число, то знак минус необходимо игнорировать.

**Ввод**

    В единственной строке задаются элементы списка через запятую с пробелом.

**Вывод**

    В единственную строку выводится сумма цифр согласно условию.

**Пример**

Ввод

    12, 104, 81

Вывод

    17

**Примечания**

Например, если дан список [12, 104, 81], то сумма всех его цифр будет равна:

1 + 2 + 1 + 0 + 4 + 8 + 1 = 17

In [ ]:
def sum_st(num):
    num = str(num)
    sum_num = 0
    
    for i in num:
        sum_num += int(i)
    
    return sum_num

spisok = list(map(int,input().split(',')))
split = str()
for i in spisok:
    if i < 0:
        i = str(abs(i))
        split += i
    else:
        i = str(i)
        split += i

print(sum_st(split))

## Задача 4

Посчитать сумму элементов каждого столбца двухмерного списка.

**Ввод**

    В первую строку, через пробел, вводится размерность двумерного списка.
    Первый элемент - количество строк, второй элемент - количество столбцов.
    Далее в каждой строке вводятся элементы строки списка, через пробел.
    Каждая новая строка списка должна вводится с новой строки.

**Вывод**

    В единственную строку через пробел выводится сумма элементов столбцов.
    Сначала сумму элементов нулевого столбца, затем первого, второго и т.д.

**Пример**

Ввод

    4 2
    1 2
    3 4
    5 6
    7 8

Вывод

    16 20

In [ ]:
strings, columns = map(int, input().split())

spisok = []
for i in range(strings):
    spisok.append(list(map(int,input().split())))

summ = [sum(i) for i in zip(*spisok)]
print(*summ)

In [ ]:
# Вариант решения без использования zip()

strings, columns = map(int, input().split())

spisok = []
for i in range(strings):
    spisok.append(list(map(int, input().split())))
    
output_val = [sum([i[b] for i in spisok]) for b in range(columns)]
print(*output_val)

## Задача 5

Заменить все отрицательные элементы в двухмерном массиве на ноль.

**Ввод**

    В первую строку, через пробел, вводится размерность двумерного списка.
    Первый элемент - количество строк, второй элемент - количество столбцов.
    Далее в каждой строке вводятся элементы строки списка, через пробел.
    Каждая новая строка списка должна вводится с новой строки.

**Вывод**

    В первой строке выводится нулевая строка списка, изменённая согласно условию, через запятую и пробел
    Во второй строке выводится первая строка списка, изменённая согласно условию, через запятую и пробел
    и т.д.

**Пример**

Ввод

    4 3
    -3 -2 1
    2 3 4
    -5 6 7
    8 9 0

Вывод

    0, 0, 1
    2, 3, 4
    0, 6, 7
    8, 9, 0

In [ ]:
n, m = map(int, input().split())

spisok = []
for i in range(n):
    spisok.append(list(map(int,input().split())))

for i in range(len(spisok)):
    for j in range(len(spisok[i])):
        if spisok[i][j] < 0:
            spisok[i][j] = 0

for i in spisok:
    print(*i, sep = ", ")

## Задача 6

Напишите программу, которая принимает на вход строку, и выводит слово, которое встречается во фразе чаще всего. Гарантируется, что такое слово будет только одно. Регистр слов не учитывается, знаки препинания в предложениях игнорируются.

**Ввод**

    В единственную строку вводится строка.

**Вывод**

    В единственную строку выводится искомое слово и то количество раз, сколько оно встретилось в тексте.
    Данные выводятся через запятую.

**Пример**

Ввод

    Напишите программу, которая принимает на вход строку, и выводит слово, которое встречается во фразе чаще всего. Гарантируется, что такое слово будет только одно. Регистр слов не учитывается, знаки препинания в предложениях игнорируются.

Вывод

    слово, 2

In [ ]:
import string
from collections import Counter

stroka = input()

cleaned_list = []
for word in stroka.split():
    cleaned_list.append(word.strip(string.punctuation).lower())

result = Counter(cleaned_list).most_common(1)

for i in result:
    print(*i, sep = ", ")

In [ ]:
# Альтернативный способ обработки вывода результата

import string
from collections import Counter

stroka = input()

cleaned_stroka = []
for word in stroka.split():
    cleaned_stroka.append(word.strip(string.punctuation).lower())

result = Counter(cleaned_stroka).most_common(1)

print('{}, {}'.format(result[0][0], result[0][1]))

## Задача 7

Предположим в языке программирования Python нет функции возведения в степень. Необходимо написать программу, в которой будет функция возводящая введенное пользователем число в введенную пользователем степень.

**Ввод**

    В первую строку вводится количество пар: число – степень
    Во вторую строку вводится число и степень, в которую его нужно возвести. Ввод производится через пробел.
    и т.д.

**Вывод**

    В первую строку выводится результат возведения числа в заданную степень.
    и т.д.

**Пример**

Ввод

    5
    5 3
    3 9
    -3 10
    100 0
    0 100

Вывод

    125
    19683
    59049
    1
    0

**Примечания**

Гарантируется, что число, которое необходимо ввести в степень целое.

Гарантируется, что степень, в которое необходимо ввести число, целое и больше или равно нулю.

In [ ]:
def exponentiation(x, y):
    return x ** y

strings = int(input())

spisok = []
for i in range(strings):
    spisok.append(list(map(int,input().split())))

x = 0
for i in range(strings):
    if x < strings:
        print(exponentiation(*spisok[x]))
        x += 1

In [ ]:
# Альтернативный способ обработки введённого списка

def exponentiation(x, y):
    return x ** y

strings = int(input())
spisok = []
for i in range(strings):
    spisok.append(list(map(int,input().split())))

result = []
for i in spisok:
    x = i[0]
    y = i[1]
    result.append(exponentiation(x, y))

for i in result:
    print(i)

# Домашнее задание 3

## Задача 1

Вычислить сумму каждой строки двумерного списка заданного случайными целыми числами.

**Ввод**

    В первой строке через пробел задается пять значений.
    Первое и второе - количество строк и столбцов двумерного списка.
    Третье - инициализатор случайных чисел.
    Четвертое и пятое – минимальное и максимальное значение для генерации случайных чисел.
    Все значения целочисленные и больше нуля.

**Вывод**

    В первой строке выводится сумма элементов нулевой строки списка.
    Во второй строке выводится сумма элементов второй строки.
    и т.д.

**Пример**

Ввод

    3 4 25 1 100

Вывод

    178
    189
    175

**Примечания**

random.seed(x) - инициализатор случайных чисел, где x значение получаемое при вводе данных.

random.randint(a, b) - возвращает случайное число из определенного диапазона.

In [ ]:
import random

lst = (list(map(int,input().split())))

random.seed(lst[2])

a = []
for i in range(lst[0]):
    b = []
    for j in range(lst[1]):
        b.append(random.randint(lst[3],lst[4]))
    print(sum(b))

## Задача 2

В соответствии с законом, принимать участие в выборах в качестве избирателя, можно по достижении 18 лет на день голосования. Необходимо написать программу, которая выведет сообщение можно ли избирателю участвовать в выборах или нет.

**Ввод**

    В первой строке задается количество рассматриваемых избирателей и дата голосования, по шаблону «3, 16.03.2024»
    Во второй строке вводится ФИО первого избирателя и дата его рождения, по шаблону «Иванов Иван Иванович, 25.01.1980»
    В третей строке вводится ФИО второго избирателя и дата его рождения, по шаблону «Петров Иван Иванович, 25.01.2020»
    и т.д.

**Вывод**

    В первой строке выводиться информация по первому избирателю по шаблону «Иванов И.И. может участвовать в выборах»
    Во второй строке выводиться информация по второму избирателю по шаблону «Петров И.И. НЕ может участвовать в выборах»
    и т.д.

**Пример 1**

Ввод

    3, 16.03.2024
    Иванов Иван Иванович, 25.01.1980
    Петров Иван Иванович, 17.03.2006
    Сидоров Иван Иванович, 16.03.2006

Вывод

    Иванов И.И. может участвовать в выборах
    Петров И.И. НЕ может участвовать в выборах
    Сидоров И.И. может участвовать в выборах

**Пример 2**

Ввод

    3, 17.03.2024
    Иванов Иван Иванович, 25.01.1980
    Петров Иван Иванович, 17.03.2006
    Сидоров Иван Иванович, 16.03.2006

Вывод

    Иванов И.И. может участвовать в выборах
    Петров И.И. может участвовать в выборах
    Сидоров И.И. может участвовать в выборах

In [ ]:
# Сырой код, хоть и рабочий, в рамках текущей задачи

import datetime

string = (list(map(str,input().split(', '))))

voter_list = []
for i in range(int(string[0])):
    voter_list.append(list(map(str,input().split(', '))))

voting_date = datetime.datetime.strptime(string[1], "%d.%m.%Y")

for i in voter_list:
    full_name = (i[0]).split(' ')
    birthday = datetime.datetime.strptime(i[1], "%d.%m.%Y")

    age = voting_date.year - birthday.year - ((voting_date.month, voting_date.day) < (birthday.month, birthday.day))

    abbreviated_name = (full_name[0] + ' ' + full_name[1][0] + '.' + full_name[2][0] + '.')

    if age >= 18:
        print(f'{abbreviated_name} может участвовать в выборах')
    else:
        print(f'{abbreviated_name} НЕ может участвовать в выборах')

In [ ]:
# Доработанная версия версия решения с комментариями

import datetime

def get_date(string_date):
    # Преобразование данных типа "строка", в тип "дата"
    formatted_date = datetime.datetime.strptime(string_date, "%d.%m.%Y")
    return formatted_date

def аbbreviation(full_name_str):
    # Получаем из полного ФИО, сокращённый вариант
    full_name_split = full_name_str.split(' ')
    reduced_name = full_name_split[0] + ' ' + full_name_split[1][0] + '.' + full_name_split[2][0] + '.'
    return reduced_name

string = input().split(', ')  # Ввод количества избирателей и даты голосования в формате «3, 16.03.2024»

voting_date = get_date(string[1])  # Преобразование даты голосования из строки в тип "дата"

voter_list = []  # Новый список, куда будем собирать ФИО и даты рождения трёх избирателей
for i in range(int(string[0])):  # string[0] указывает, данных скольких участников будут введены и помещены в список
    voter_list.append(input().split(', '))

voter_list_result = []  # Новый список, куда будем собирать результаты for
for voter in voter_list:
    birthday = get_date(voter[1])  # Преобразование даты рождения избирателя из строки в тип "дата"
    
    # Проверяем, есть ли избирателю полные 18 лет на дату голосования
    if (voting_date.year - birthday.year - ((voting_date.month, voting_date.day) < (birthday.month, birthday.day))) >= 18:
        get_voter_list = f"{аbbreviation(voter[0])} может участвовать в выборах"
    else:
        get_voter_list = f"{аbbreviation(voter[0])} НЕ может участвовать в выборах"
    voter_list_result.append(get_voter_list)  # Собираем результаты в итоговый список

print(*voter_list_result, sep="\n")  # Распаковываем итоговый список и выводим результат каждого избирателя на новой строке

## Задача 3

Найдите наибольший общий делитель.

**Ввод**

    В единственную строку вводится два целочисленных положительных числа через пробел.

**Вывод**

    В единственную строку выводится их наибольший общий делитель.

**Пример**

Ввод

    594 7920

Вывод

    198

In [ ]:
import math

a, b = map(int, input().split(' '))
print(math.gcd(a, b))

p.s. Про способы нахождения НОД (наибольший общий делитель) можно ещё почитать по [ссылке](https://pythonpip.ru/examples/nod-dvuh-chisel-v-python)

# Домашнее задание 4

## Задача 1

Работаем с локальным файлом `Набор_данных_по_Kaggle_120_летняя_история_Олимпийский_игр.csv` [ссылка на файл](https://disk.yandex.ru/i/ypxELGTJk5ojmA)

Найдите сколько всего строк в таблице не считая заголовка.

In [ ]:
import pandas as pd

input_data = pd.read_csv("Набор_данных_по_Kaggle_120_летняя_история_Олимпийский_игр.csv")

input_data.shape

## Задача 2

Найдите сколько всего лет было самому молодому участнику олимпийских игр?

    Олимпийские игры 1994 года, пол мужской
    Олимпийские игры 1992 года, пол мужской
    Олимпийские игры 1996 года, пол женский

In [ ]:
# Код для поиска ответов на вопросы. Нужно лишь указать необходимый пол и год

import pandas as pd

input_data = pd.read_csv("Набор_данных_по_Kaggle_120_летняя_история_Олимпийский_игр.csv")

sorted_data = input_data[(input_data.Sex == 'M') & (input_data.Year == 1992)]
sorted_data.sort_values(by=['Age'], ascending=True)

## Задача 3

Какую долю составляют (не в процентах) соревнования по мужской спортивной гимнастике среди всех участников игр 1904 года? Округлите ответ до двух знаков после точки.

Подсказка: вам необходимы соревнования «Gymnastics Men's Individual All-Around, Apparatus Work»

In [ ]:
import pandas as pd

input_data = pd.read_csv("Набор_данных_по_Kaggle_120_летняя_история_Олимпийский_игр.csv")

count_gym_men = input_data[(input_data.Event == "Gymnastics Men's Individual All-Around, Apparatus Work")].shape
count_event_to_year= input_data[(input_data.Year == 1904)].shape

print(count_gym_men[0] / count_event_to_year[0])  # Результат после округления 0.09

## Задача 4

Найдите среднее арифметическое для роста девушек баскетболисток (название соревнования должно начинаться со слова «Basketball»), которые участвовали в играх 1988 года. Округлите ответ до двух знаков после точки.

In [ ]:
import pandas as pd

input_data = pd.read_csv("Набор_данных_по_Kaggle_120_летняя_история_Олимпийский_игр.csv")

sorted_data = input_data[(input_data.Sex == 'F') & (input_data.Year == 1988) & (input_data.Sport == 'Basketball')]

print(round(sorted_data[["Height"]].mean(), 2))  # Результат после округления 181.51

## Задача 5

Найдите самую тяжелую (по весу) спортсменку игр 2008 года. В каком виде спорта она участвовала? Скопируйте в ответ название.

In [ ]:
import pandas as pd

input_data = pd.read_csv("Набор_данных_по_Kaggle_120_летняя_история_Олимпийский_игр.csv")

sorted_data = input_data[(input_data.Sex == 'F') & (input_data.Year == 2008)]

sorted_data.sort_values(by=['Weight'], ascending=False).head(5)

## Задача 6

Найдите соответствие. В скольких олимпиадах приняли участие?

    Aleksey Yuryevich Nemov
    Aleksey Petrovich Bondarenko
    Darya Vitalyevna Pishchalnikova

In [ ]:
import pandas as pd

input_data = pd.read_csv("Набор_данных_по_Kaggle_120_летняя_история_Олимпийский_игр.csv")

sorted_data = input_data[(input_data.Name == 'Aleksey Yuryevich Nemov')]

list_year = sorted_data.loc[1:, 'Year']

year_count = pd.unique(list_year)

year_unique = 0
for year in year_count:
    year_unique += 1

print(year_unique)

## Задача 7

Сколько золотых медалей в борьбе (Wrestling) выиграла Россия на Олимпиаде в 2008 году?

In [ ]:
import pandas as pd

input_data = pd.read_csv("Набор_данных_по_Kaggle_120_летняя_история_Олимпийский_игр.csv")

sorted_data = input_data[(input_data.NOC == 'RUS')  & (input_data.Year == 2008) & (input_data.Medal == 'Gold') & (input_data.Sport == 'Wrestling')]

list_ID = sorted_data.loc[1:, 'ID']

ID_count = pd.unique(list_ID)

ID_unique = 0
for year in ID_count:
    ID_unique += 1

print(ID_unique)

## Задача 8

Найдите разницу между количеством уникальных видов спорта на играх в 2004 и в 1972 годах.

In [ ]:
import pandas as pd

input_data = pd.read_csv("Набор_данных_по_Kaggle_120_летняя_история_Олимпийский_игр.csv")

sorted_data_1 = input_data[(input_data.Year == 2004)]
sorted_data_2 = input_data[(input_data.Year == 1972)]

list_Sport_1 = sorted_data_1.loc[1:, 'Sport']

Sport_count_1 = pd.unique(list_Sport_1)

Sport_unique_1 = 0
for year in Sport_count_1:
    Sport_unique_1 += 1

list_Sport_2 = sorted_data_2.loc[1:, 'Sport']

Sport_count_2 = pd.unique(list_Sport_2)

Sport_unique_2 = 0
for year in Sport_count_2:
    Sport_unique_2 += 1

print(Sport_unique_1 - Sport_unique_2)

# Для большей красоты, for можно вынести в отдельную функцию

# Домашнее задание 5

## Задача 1

Определить является ли строка палиндромом.

**Ввод**

    В единственной строке задается строка с текстом.

**Вывод**

    В единственной строке выводится True если строка является палиндромом и False если не является палиндромом.

**Пример 1**

Ввод

    А роза упала на лапу Азора...

Вывод

    True

**Пример 2**

Ввод

    Привет мир!!!

Вывод

    False

**Примечание**

Регистр слов не учитывается, знаки препинания и пробелы в строке необходимо исключить.

In [ ]:
import string

def Palindrom(line):
    if  line == line[::-1]:
        return True
    else:
        return False

text = input()

punctuation_cleaning = text.translate(str.maketrans('', '', '!"#$%&)(*+, -./:;<=>?@[\]^_`{|}~'))
clearing_spaces = punctuation_cleaning.strip().lower()

print(Palindrom(clearing_spaces))

## Задача 2

Дана строка, посчитать сколько в ней гласных букв.

**Ввод**

    В единственной строке задается строка с текстом.

**Вывод**

    В единственной строке выводится количество гласных букв или -1 если их нет.

**Пример**

Ввод

    привет мир!!!

Вывод

    3

**Примечания**

Следующие буквы считаются гласными: а, у, о, ы, и, э, я, ю, ё, е.

Гарантируется, что текст будет состоять из цифр, знаков препинание и букв русского алфавита

In [ ]:
text = input()

count = 0
vowels = set("ауоыиэяюёе")
for letter in text.lower():
    if letter in vowels:
        count += 1

if count >= 1:
    print(count)
else:
    print(-1)

## Задача 3

По заданным позициям элемента в двумерном списке необходимо вывести значение этого элемента или же указать, что такого элемента нет.

**Ввод**

    В первую строку, через пробел, вводится размерность двумерного списка и позиции элемента.
    Первый элемент - количество строк, второй элемент - количество столбцов, третий элемент - позиция по строке, четвертый элемент – позиция по столбцу.
    Далее в каждой строке вводятся элементы строки списка, через пробел.
    Каждая новая строка списка должна вводится с новой строки.

**Вывод**

    В единственную строку выводится значение элемента или сообщение «Позиция выходит за пределы списка».

**Пример 1**

Ввод

    3 2 0 1
    1 2
    3 4
    5 6

Вывод

    2

**Пример 2**

Ввод

    3 2 5 1
    1 2
    3 4
    5 6

Вывод

    Позиция выходит за пределы списка

In [ ]:
max_lines, max_columns, line_item, column_item = map(int, input().split())

spisok = []
for element in range(max_lines):
    spisok.append(list(map(int,input().split())))

if max_lines <= line_item or max_columns <= column_item:
    print('Позиция выходит за пределы списка')
elif line_item < 0 or column_item < 0:
    if (0 - max_lines) > line_item or (0 - max_columns) > column_item:
        print('Позиция выходит за пределы списка')
    else:
        print(spisok[line_item][column_item])
else:
    print(spisok[line_item][column_item])

## Задача 4

Кодирование строки.

Кодирование осуществляется следующим образом, подается строка 'aaaabbсaa' преобразуется в 'a4b2с1a2', то есть группы одинаковых символов исходной строки заменяются на этот символ и количество его повторений в этой позиции строки.

**Ввод**

    В единственную строку вводится первоначальная строка, которую необходимо закодировать.

**Вывод**

    В единственную строку выводится итоговая закодированная строка.

**Пример 1**

Ввод

    aaaabbcaa

Вывод

    a4b2c1a2

**Пример 2**

Ввод

    абв

Вывод

    а1б1в1

**Примечания**

Гарантируется, что входная строка будет состоять из букв русского и английского языка в нижнем регистре.

Гарантируется, что длина строки будет больше или равна одному символу.

In [ ]:
from itertools import groupby

text = input()

res = "".join([f"{letter}{len(list(repeat))}" for letter, repeat in groupby(text)])
print(res)

Про **groupby()** информация по [ссылке](https://docs-python.ru/standart-library/modul-itertools-python/funktsija-groupby-modulja-itertools/)

## Задача 5

Напишите простой калькулятор, который считывает с пользовательского ввода три строки: первое число, второе число и операцию, после чего применяет операцию к введённым числам ("первое число" "операция" "второе число") и выводит результат на экран (в консоль).

Поддерживаемые операции: +, -, /, *, mod, pow, div, где

    mod — это взятие остатка от деления,
    pow — возведение в степень,
    div — целочисленное деление.

Если выполняется деление и второе число равно 0, необходимо выводить строку "Деление на 0!".

Если операция не определена, то выводится сообщение «Ошибка ввода».

Обратите внимание, что на вход программе приходят вещественные числа.

**Ввод**

    В первою строку вводится первое число.
    Во вторую строку вводится второе число.
    В третью строку вводится операция.

**Вывод**

    В единственную строку выводится результат.

**Пример 1**

Ввод

    5
    5
    +

Вывод

    10.0

**Пример 2**

Ввод

    5
    0
    /

Вывод

    Деление на 0!

**Пример 3**

Ввод

    5
    5
    5

Вывод

    Ошибка ввода

In [ ]:
def calculator(number1, number2, operator):
    
    number1, number2 = float(number1), float(number2)
    
    if operator == "+":
        result = number1 + number2
    elif operator == "-":
        result = number1 - number2
    elif operator == "*":
        result = number1 * number2
    elif operator == "/":
        if number2 == 0:
            result = "Деление на 0!"
        else:
            result = number1 / number2
    elif operator == "mod":
        if number2 == 0:
            result = "Деление на 0!"
        else:
            result = number1 % number2
    elif operator == "pow":
        result = number1 ** number2
    elif operator == "div":
        if number2 == 0:
            result = "Деление на 0!"
        else:
            result = number1 // number2
    else:
        result = "Ошибка ввода"
    
    return(result)

number1 = input()
number2 = input()
operator = input()

print(calculator(number1, number2, operator))